name: grav_comp_hw

dynamixel:
  # USB port name given by the command: ls /dev/serial/by-id/
  dynamixel_port: "usb-FTDI_USB__-__Serial_Converter_FTA2U4GA-if00-port0"
  # Servo types
  servo_types: [
    "XC330_T288_T", "XM430_W210_T", "XM430_W210_T",
    "XC330_T288_T", "XC330_T288_T", "XC330_T288_T", "XC330_T288_T"
  ]
  # Servo joint directions to match that of the leader arm
  joint_signs: [1, -1, -1, -1, 1, 1, 1]

arm_teleop:
  # URDF used for creating leader arm dynamics model to compute gravity compensation
  leader_urdf: "gello/factr/urdf/yam_active_gello/robot.urdf"
  num_arm_joints: 6
  arm_joint_limits_max: [3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159]
  arm_joint_limits_min: [-3.14159, -3.14159, -3.14159, -3.14159, -3.14159, -3.14159]
  arm_joint_limits_safety_margin: 0.1
  initialization:
    # These are your start positions (URDF coordinates) - offsets will be auto-calculated
    calibration_joint_pos: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    initial_match_joint_pos: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

gripper_teleop:
  # The maximum range (in rad) of the leader gripper trigger
  actuation_range: 0.8

controller:
  frequency: 500
  torque_feedback:
    enable: False
    gain: 3.0
    damping: 0.0
    motor_scalar: 94.5652173913
  gravity_comp:
    enable: True
    gain: 0.6
  null_space_regulation:
    null_space_joint_target: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
    kp: 0.0
    kd: 0.0
  static_friction_comp:
    enable_speed:   0.0
    gain: 0.0
  joint_limit_barrier:
    kp: 0.0
    kd: 0.0
  joint_position_control:
    interpolation_step_size: 0.01
    kp: 1.03561658022
    kd: 0.04315069084

  gripper_feedback:
    enable: True

teleop:
  enable: true
  hz: 30
  wait_for_server_timeout_s: 5.0
  robot:
    _target_: gello.robots.yam.YAMRobot
    channel: can_right
  mapping:
    # Map leader joints to follower joints
    index_map: [0, 1, 2, 3, 4, 5]
    # Signs to align sim/hardware with leader frames
    signs: [1, 1, -1, -1, 1, 1]
    # Additional offsets (radians) applied to follower after signs
    offsets: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    # Auto-align offsets at startup so follower matches current leader pose
    auto_align: true
  # Explicit gripper config for teleop normalization: [id, open_deg, close_deg]
  gripper_config: [7, 241.4375, 300.9375] 
