robot:
  _target_: gello.robots.yam.YAMRobot
  channel: "can_right"
agent:
  _target_: gello.agents.gello_agent.GelloAgent
  port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FTAA0B5Y-if00-port0
  dynamixel_config:
    _target_: gello.agents.gello_agent.DynamixelRobotConfig
    joint_ids: [1, 2, 3, 4, 5, 6]
    joint_offsets: [3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159]
    joint_signs: [1.0, -1.0, 1.0, 1.0, 1.0, 1.0]
    gripper_config: [7, -34.1875, 25.3125]
  start_joints: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
hz: 30
max_steps: 1000
