/**:
  controller_manager:
    ros__parameters:
      update_rate: 500  # Hz
      joint_state_broadcaster_robotiq:
        type: joint_state_broadcaster/JointStateBroadcaster
        parameters:
          publish_topic: "gripper_joint_states"
      robotiq_gripper_controller:
        type: position_controllers/GripperActionController
      robotiq_activation_controller:
        type: robotiq_controllers/RobotiqActivationController

/**:
  robotiq_gripper_controller:
    ros__parameters:
      default: true
      joint: robotiq_85_left_knuckle_joint
      use_effort_interface: true
      use_speed_interface: true

/**:
  robotiq_activation_controller:
    ros__parameters:
      default: true
